version: '3.8'
services:
    one-coupon-postgres:
        image: registry.cn-shenzhen.aliyuncs.com/l7-bug-tool/postgres  # 推荐使用特定版本（如Alpine减小体积）
        environment:
            POSTGRES_USER: admin           # 管理员用户名
            POSTGRES_PASSWORD: 123456  # 强密码建议
            TZ: Asia/Shanghai              # 时区设置
        volumes:
            - one-coupon-postgres-data:/var/lib/postgresql/data  # 核心数据持久化
        ports:
            - "17000:5432"  # 主机端口:容器端口
        networks:
            - one-coupon-network
        healthcheck: # 健康状态检测
            test: [ "CMD-SHELL", "pg_isready -U admin" ]
            interval: 5s
            timeout: 3s
            retries: 5
        restart: always                 # 自动重启保障服务可用性

    one-coupon-redis:
        image: registry.cn-shenzhen.aliyuncs.com/public-image-l/redis
        restart: always                 # 自动重启保障服务可用性
        ports:
            - "17001:6379"      # 暴露默认端口
        volumes:
            - one-coupon-redis-data:/data              # 数据持久化目录
        environment:
            - TZ=Asia/Shanghai         # 时区设置
        networks:
            - one-coupon-network

    one-coupon-nacos:
        image: nacos/nacos-server:v2.2.3  # 推荐指定版本号
        environment:
            - MODE=standalone             # 关键！指定单机模式
            - PREFER_HOST_MODE=hostname   # 避免IP识别问题
        ports:
            - "17002:8848"                 # Web控制台端口
            - "17003:9848"                 # gRPC通信端口（Nacos 2.0+必需）
        volumes:
            - ./.nacos-data:/home/nacos/data     # 数据持久化目录
            - ./.nacos-logs:/home/nacos/logs     # 日志持久化目录
        restart: always                 # 自动重启保障服务可用性
        networks:
            - one-coupon-network
volumes:
    one-coupon-postgres-data:  # 命名卷确保数据安全
    one-coupon-redis-data:  # 命名卷确保数据安全

networks:
    one-coupon-network: # 隔离网络提升安全性
        driver: bridge