version: '3.8'
services:
    dev-redis:
        image: redis:7-alpine  # 使用特定版本
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - dev-redis-data:/data
        environment:
            - TZ=Asia/Shanghai
            - REDIS_PASSWORD=  # 如果需要密码验证
        command: redis-server --bind 0.0.0.0 --requirepass ""  # 显式配置
        networks:
            - dev-network

volumes:
    dev-redis-data:

networks:
    dev-network:
        external: true