version: '3.8'
services:
    dev-redis:
        image: redis
        restart: always                 # 自动重启保障服务可用性
#        ports:
#            - "16379:6379"      # 暴露默认端口
        volumes:
            - dev-redis-data:/data              # 数据持久化目录
        environment:
            - TZ=Asia/Shanghai         # 时区设置
        network_mode: "host"
volumes:
    dev-redis-data:  # 命名卷确保数据安全