version: '3.8'
services:
    dev-redis:
        image: redis:8-alpine  # 使用特定版本
        restart: always
        volumes:
            - dev-redis-data:/data
        ports:
            - "6379:6379"      # 暴露默认端口
        environment:
            - TZ=Asia/Shanghai
        networks:
            - dev-network

volumes:
    dev-redis-data:

networks:
    dev-network:
        external: true