version: '3.8'
services:
    dev-postgres-1:
        image: postgres:18
        restart: always
#        ports:
#            - "15432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123456
            TZ: Asia/Shanghai
            PGTZ: Asia/Shanghai
        networks:
            - dev-network
        volumes:
            - dev-postgres-data-1:/var/lib/postgresql/18/docker
    dev-postgres-2:
        image: postgres:18
        restart: always
#        ports:
#            - "15432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123456
            TZ: Asia/Shanghai
            PGTZ: Asia/Shanghai
        networks:
            - dev-network
        volumes:
            - dev-postgres-data-2:/var/lib/postgresql/18/docker

volumes:
    dev-postgres-data-1:  # 命名卷确保数据安全
    dev-postgres-data-2:  # 命名卷确保数据安全

networks:
    dev-network: # 隔离网络提升安全性
        external: true  # 关键：声明此网络已在外部创建
