version: '3.8'
services:
    one-coupon-file:
        image: one-coupon-file:1.0-SNAPSHOT
        container_name: one-coupon-file # 建议加上，方便在其他容器中通过主机名访问
        network_mode: "host"             # 关键配置：使用主机网络模式
        environment:
            TZ: Asia/Shanghai
        restart: always
        # 注意: 使用 host 模式后，ports 映射将失效，必须删除
        networks:
            one-coupon-network:         # 同时连接到自定义网络
                aliases:
                    - one-coupon-file   # 可选项：在网络中设置别名

networks:
    one-coupon-network:
        external: true