# http://trilium.local
version: "3.9"

services:
    trilium:
        ports:
            - "28888:8080"
        image: registry.cn-shenzhen.aliyuncs.com/public-image-l/trilium:latest  # 使用 trilium 镜像
        container_name: trilium  # 容器名称
        restart: always  # 容器异常退出时自动重启
        volumes:
            - ./.trilium-data:/home/node/trilium-data  # 将本地的 trilium-data 持久化到容器
