version: '3.8'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4  # 指定版本
        container_name: elasticsearch
        environment:
            - discovery.type=single-node      # 单节点模式
            - ES_JAVA_OPTS=-Xms1g -Xmx1g       # JVM 内存限制
            - xpack.security.enabled=false     # 禁用安全认证（开发环境）
            #- ELASTIC_PASSWORD=your_password  # 启用时设置密码
        volumes:
            - es_data:/usr/share/elasticsearch/data  # 数据持久化
        ports:
            - "9200:9200"   # HTTP API 端口
            - "9300:9300"   # 集群通信端口
        ulimits:
            memlock:
                soft: -1
                hard: -1

volumes:
    es_data: # 数据卷声明
        driver: local