version: '3.8'
services:
    nacos:
        image: nacos/nacos-server:v2.2.3  # 推荐指定版本号
        container_name: nacos-standalone
        environment:
            - MODE=standalone             # 关键！指定单机模式
            - PREFER_HOST_MODE=hostname   # 避免IP识别问题
        ports:
            - "8848:8848"                 # Web控制台端口
            - "9848:9848"                 # gRPC通信端口（Nacos 2.0+必需）
        volumes:
            - ./.nacos-data:/home/nacos/data     # 数据持久化目录
            - ./.nacos-logs:/home/nacos/logs     # 日志持久化目录
        restart: always                 # 自动重启保障服务可用性