version: '3.3'
services:
  alist:
    image: 'registry.cn-shenzhen.aliyuncs.com/l7-bug-tool/alist:0.03'
    container_name: alist
    volumes:
      - './.alist-data:/opt/alist/data'
    ports:
      - '5244:5244'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    restart: unless-stopped