version: '3.8'
services:
    one-coupon-file:
        image: one-coupon/file-core:1.0-SNAPSHOT
        container_name: one-coupon-file
        network_mode: "host"
        environment:
            TZ: Asia/Shanghai
            SPRING_PROFILES_ACTIVE: docker-host
        restart: always
        volumes:
            - one-coupon-java:/tmp/logs
    one-coupon-app-log:
        image: one-coupon/app-log:1.0-SNAPSHOT
        container_name: one-coupon-app-log
        network_mode: "host"
        environment:
            TZ: Asia/Shanghai
        restart: always
        volumes:
            - one-coupon-java:/tmp/logs
    one-coupon-gateway:
        image: one-coupon/gateway:1.0-SNAPSHOT
        container_name: one-coupon-gateway
        network_mode: "host"
        environment:
            TZ: Asia/Shanghai
            SPRING_PROFILES_ACTIVE: docker
        restart: always
        volumes:
            - one-coupon-java:/tmp/logs
volumes:
    one-coupon-java:
networks:
    one-coupon-network: # 隔离网络提升安全性
        external: true  # 关键：声明此网络已在外部创建