version: '3.8'
services:
    minio:
        image: minio/minio:RELEASE.2025-07-23T15-54-02Z # 建议指定最新稳定版本，例如 RELEASE.2024-02-14T21-36-02Z
        container_name: minio
        restart: unless-stopped # 容器退出时总是重启，确保服务高可用
        ports:
            - "19000:9000" # MinIO API 端口，用于 S3 兼容接口（上传/下载文件）
            - "19001:9001" # MinIO 控制台端口（Web 管理界面）
        environment:
            MINIO_ROOT_USER: minio_admin # 管理员用户名，生产环境请务必修改
            MINIO_ROOT_PASSWORD: 123456789 # 管理员密码，生产环境请务必使用强密码
            TZ: Asia/Shanghai # 可选：设置容器时区
        volumes:
            # 单机模式：挂载一个数据目录
            - minio-data:/data
        command: server /data --console-address ":9001"
        # 多磁盘模式的启动命令（需与卷挂载匹配）[2](@ref)
        # command: server http://minio/data{1...4} --console-address ":9001"
        networks:
            - minio-net

# 定义网络，便于其他容器访问
networks:
    minio-net:
        driver: bridge

volumes:
    minio-data: