services:
  bilibili_tool:
    image: registry.cn-shenzhen.aliyuncs.com/l7-bug-tool/bilibili-tool-pro:0.02
    container_name: bili
    restart: unless-stopped
    tty: true
    volumes:
      - ./.app-data/Logs:/app/Logs
      - ./.app-data/appsettings.json:/app/appsettings.json
      - ./.app-data/cookies.json:/app/cookies.json
    environment:
      Ray_BiliBiliCookies: somecookies
      Ray_Crontab: |
        0 6 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=Daily >> /var/log/cron.log
        30 6 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=VipBigPoint >> /var/log/cron.log
        30 15,21 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=LiveFansMedal >> /var/log/cron.log
