version: '3.8'

services:
    redis:
        image: registry.cn-shenzhen.aliyuncs.com/public-image-l/redis
        container_name: redis-test
        restart: unless-stopped
        ports:
            - "26379:6379"      # 暴露默认端口
        volumes:
            - ./.data:/data              # 数据持久化目录
        environment:
            - TZ=Asia/Shanghai         # 时区设置
        sysctls: # 性能优化参数
            - net.core.somaxconn=1024