version: '3.8'

services:
    redis:
        image: registry.cn-shenzhen.aliyuncs.com/public-image-l/redis
        container_name: redis-test
        restart: unless-stopped
        ports:
            - "6379:26379"      # 暴露默认端口
        volumes:
            - ./data:/data              # 数据持久化目录
        command: redis-server /usr/local/etc/redis/redis.conf
        environment:
            - TZ=Asia/Shanghai         # 时区设置
            - REDIS_PASSWORD=test1234   # 测试环境密码（按需修改）
        sysctls: # 性能优化参数
            - net.core.somaxconn=1024