version: '3.8'
services:
    one-coupon-app-log:
        image: one-coupon-app-log:1.0-SNAPSHOT
        container_name: one-coupon-app-log
        network_mode: "host"
        environment:
            TZ: Asia/Shanghai              # 时区设置
        restart: always                 # 自动重启保障服务可用性